version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: Simulacro
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # app:
  #   build: .
  #   container_name: nest_js_app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MONGO_URL=mongodb://mongodb:27017/library
  #   depends_on:
  #     - mongodb

volumes:
  mongo-data: